---
- import_playbook: playbooks/base.yml
  tags: [base]

- import_playbook: playbooks/dom0.yml
  tags: [dom0]

- import_playbook: playbooks/firefox.yml
  tags: [firefox]

- import_playbook: playbooks/llm.yml
  tags: [llm]

- import_playbook: playbooks/ocr.yml
  tags: [ocr]

- import_playbook: playbooks/sys_gpu.yml
  tags: [sys-gpu]

- import_playbook: playbooks/messenging.yml
  tags: [messenging]

- import_playbook: playbooks/claude_desktop.yml
  tags: [claude-desktop]

- import_playbook: playbooks/work.yml
  tags: [work]
