---
vpn_base_template: "fedora-{{ fedora_version }}-gnome"
host_vpn_template: "vpn-template-{{ vpn_base_template }}"
host_vpn_dvm: vpn-dvm
vpn_dispvm: vpn-disp
host_vpn_dvm_ch: vpn-ch-dvm
vpn_dispvm_ch: vpn-ch-disp
vpn_vcpus: 1
