---
- name: Check if binds directory exists
  ansible.builtin.file:
    path: "{{ binds_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Check if bind file exists
  file:
    path: "{{ binds_file }}"
    state: touch
- name: Set bind for /usr/share/ollama
  lineinfile:
    path: "{{ binds_file }}"
    regexp: "ollama"
    line: "binds+=( '/usr/share/ollama' )"
    state: present
