all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local

    appvms:
      hosts:
        burp-dvm:
        claude-code:
        claude-desktop-app:
        data:
        debian-12-xfce-everything-dvm:
        default-dvm:
        default-mgmt-dvm:
        dev:
        llm-dvm:
        messenging:
        ocr-dvm:
        personal:
        sys-gpu-dvm:
        sys-vpn-proton-ch-dvm:
        sys-vpn-proton-fr-dvm:
        ubuntu-web-dolphinslabs:
        ubuntu-web-dvm:
        untrusted:
        work-app:
        youtube:
      vars:
        ansible_connection: qubes

    templatevms:
      hosts:
        burp-template:
        claude-code-template:
        claude-desktop-template:
        debian-12-minimal:
        debian-12-xfce:
        debian-12-xfce-dev:
        debian-12-xfce-everything:
        debian-12-xfce-nextcloud:
        debian-12-xfce-proxy:
        debian-13-xfce:
        fedora-41-xfce:
        fedora-41-xfce-audio:
        fedora-41-xfce-messenging:
        fedora-41-xfce-net:
        fedora-41-xfce-proton:
        fedora-42-xfce:
        fedora-43-xfce:
        fedora-43-xfce-messenging:
        llm-template-debian-13-xfce:
        ocr-template-debian-13-xfce:
        questing-minimal:
        sys-gpu-template:
        ubuntu-web:
        windows_11_ltsc:
        work-template:
      vars:
        ansible_connection: qubes

    standalonevms:
      hosts:
        windows_11_ltsc_lightroom:
        windows_11_ltsc_sketchup:
      vars:
        ansible_connection: qubes

    windows_vms:
      hosts:
        windows_11_ltsc:
        windows_11_ltsc_lightroom:
        windows_11_ltsc_sketchup:
      vars:
        ansible_connection: qubes

    disp_vms:
      hosts:
        burp-disp:
        disp-sys-vpn-proton-ch:
        disp-sys-vpn-proton-fr:
        llm-disp:
        ocr-disp:
      vars:
        ansible_connection: qubes
