---
nvidia_cuda_url: "https://developer.download.nvidia.com/compute/cuda/repos/debian{{ debian_version }}/x86_64/cuda-keyring_1.1-1_all.deb"

llm_template_packages_debian:
  - passwd
  - htop
  - nvtop
# Installed after the CUDA repository is added
llm_template_nvidia_packages_debian:
  - nvidia-driver-cuda
  - nvidia-kernel-dkms
