---
- hosts: "templatevms:standalonevms:!windows_vms"
  connection: qubes
  roles:
    - role: base_packages
    - role: firefox
      vars:
        firefox_extra_extensions:
          - fireshot
          - print_edit_we

- hosts: local
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - include_role:
        name: set_prefs
        apply:
          tags: [prefs, base]
      tags: [prefs]
      vars:
        target_vm: "{{ item }}"
        vm_qrexec_timeout: "{{ qrexec_timeout_default }}"
      loop: "{{ groups['appvms'] + groups['templatevms'] + groups['standalonevms'] + groups['windows_vms'] + groups['disp_vms']}}"

    - include_role:
        name: set_prefs
        apply:
          tags: [prefs, base]
      tags: [prefs]
      vars:
        target_vm: "{{ item.vm }}"
        vm_maxmem: "{{ item.maxmem | default('') }}"
        vm_memory: "{{ item.memory | default('') }}"
        vm_vcpus: "{{ item.vcpus | default('') }}"
      loop: "{{ vm_resource_config }}"
