---
#
# Template
#
- hosts: local
  connection: local
  vars_files:
    - vars/data.yml
  tasks:
    - name: Check if Template exists
      ansible.builtin.shell: "qvm-ls --raw-data --fields name | grep -w '{{ host_data_template }}$'"
      register: template_check
      failed_when: false
      changed_when: false
    - include_tasks: tasks/clone_template.yml
      vars:
        clone_src: "{{ base_template }}"
        clone_dest: "{{ host_data_template }}"
    - include_role:
        name: set_prefs
        apply:
          tags: [prefs, data]
      tags: [prefs]
      vars:
        target_vm: "{{ host_data_template }}"
        vm_root_storage: "{{ system_storage if template_check.rc != 0 else '' }}"

- hosts: "{{ host_data_template | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/data.yml
  roles:
    - role: common
    - role: base_packages
      vars:
        base_packages_playbook_extra: "{{ data_packages }}"
    - role: firefox
      vars:
        firefox_extra_extensions:
          - fireshot
          - print_edit_we

    #- role: data

- hosts: local
  connection: local
  vars_files:
    - vars/data.yml
  tasks:
    - name: Shutdown the Template
      qubesos:
        guest: "{{ host_data_template }}"
        state: shutdown
    - name: Remove the network
      ansible.builtin.command: qvm-prefs {{ host_data_template }} netvm ''

#
# AppVM
#
- hosts: local
  connection: local
  vars_files:
    - vars/data.yml
  tasks:
    - name: Check if AppVM exists
      ansible.builtin.shell: "qvm-ls --raw-data --fields name | grep -w '{{ host_data_app }}$'"
      register: app_check
      failed_when: false
      changed_when: false
    - name: Create AppVM
      ansible.builtin.command: qvm-create --class AppVM --label {{ label }} --template {{ host_data_template }} {{ host_data_app }}
      when: app_check.rc != 0
    - name: Set AppVM network
      ansible.builtin.command: qvm-prefs {{ host_data_app }} netvm {{ netvm_native }}
    - include_role:
        name: set_prefs
        apply:
          tags: [prefs, data]
      tags: [prefs]
      vars:
        target_vm: "{{ host_data_app }}"
        vm_qrexec_timeout: "{{ qrexec_timeout_default }}"
        vm_vcpus: "{{ vcpus }}"
        vm_private_storage: "{{ private_storage if app_check.rc != 0 else '' }}"

- hosts: "{{ host_data_app | default([]) }}"
  connection: qubes
  roles:
    - role: common
    - role: xfce

- hosts: local
  connection: local
  vars_files:
    - vars/data.yml
  tasks:
    - include_role:
        name: appsmenu_add
      vars:
        appsmenu_add_target_vm: "{{ host_data_app }}"
        appsmenu_add_applications: "{{ data_appsmenu_whitelist }}"

- hosts: local
  connection: local
  tasks:
    - name: Shutdown the Data AppVM
      qubesos:
        guest: "{{ host_data_app }}"
        state: shutdown
