---
- hosts: "{{ host_messenging_template }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/messenging.yml
  roles:
    - role: base_packages

- hosts: local
  connection: local
  vars_files:
    - vars/messenging.yml
  tasks:
    - name: Create a template for messenging VM
      qubesos:
        guest: "{{ host_messenging_template }}"
        state: present
        vmtype: "TemplateVM"
        properties:
          template: "{{ messenging_base_template }}"
          label: blue
      when: 0 > 1

- hosts: "{{ host_messenging_template }}"
  connection: qubes
  vars_files:
    - vars/messenging.yml
  tasks:
    - name: Install third party repositories
      become: yes
      dnf:
        name: fedora-workstation-repositories
        state: present
    - name: Enable Google Chrome repository
      become: yes
      command:
        cmd: dnf config-manager setopt google-chrome.enabled=1
    - name: Install Chrome (used for Teams)
      become: yes
      dnf:
        name: google-chrome-stable
        state: present
    - name: Install SNAP
      become: yes
      dnf:
        name:
          - snapd
          - qubes-snapd-helper
        state: present
    - name: Create SNAP Symlink
      become: yes
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
    - name: Reboot after SNAP installation
      reboot:
        reboot_timeout: 300
    - name: Install Snap Signal
      become: yes
      community.general.snap:
        name: signal-desktop
        state: present
    - name: Install Snap Whatsie
      become: yes
      community.general.snap:
        name: whatsie
        state: present

- hosts: local
  connection: local
  vars_files:
    - vars/messenging.yml
  tasks:
    - name: Create messenging AppVM
      qubesos:
        guest: "{{ host_messenging_vm }}"
        state: present
        properties:
          template: "{{ host_messenging_template }}"
          label: blue
          netvm: "{{ messenging_netvm }}"

- hosts: "{{ host_messenging_vm }}"
  connection: qubes
  vars_files:
    - vars/messenging.yml
  tasks:
    - name: Make sure autostart folder exists
      file:
        path: "/rw/home/user/.config/autostart"
        state: directory
        mode: 0755
    - name: Create autostart Signal symlink
      file:
        src: "/var/lib/snapd/desktop/applications/signal-desktop_signal-desktop.desktop"
        dest: "/rw/home/user/.config/autostart/signal.desktop"
        state: link
    - name: Create autostart Whatsie symlink
      file:
        src: "/var/lib/snapd/desktop/applications/whatsie_whatsie.desktop"
        dest: "/rw/home/user/.config/autostart/whatsie.desktop"
        state: link
    - name: Create autostart Google Chrome symlink
      file:
        src: "/usr/share/applications/google-chrome.desktop"
        dest: "/rw/home/user/.config/autostart/google-chrome.desktop"
        state: link
