---
#
# Template
#
- hosts: local
  connection: local
  vars_files:
    - vars/sys_gpu.yml
  tasks:
    - include_tasks: tasks/clone_template.yml
      vars:
        clone_src: "{{ sys_gpu_base_template }}"
        clone_dest: "{{ host_sys_gpu_template }}"

- hosts: "{{ host_sys_gpu_template | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/sys_gpu.yml
  roles:
    - role: common
    - role: base_packages
    - role: sys_gpu

- hosts: local
  connection: local
  vars_files:
    - vars/sys_gpu.yml
  tasks:
    - name: Shutdown the Template
      qubesos:
        guest: "{{ host_sys_gpu_template }}"
        state: shutdown
    - name: Remove network access
      command: qvm-prefs {{ host_sys_gpu_template }} netvm ''

#
# DVM
#
- hosts: local
  connection: local
  vars_files:
    - vars/sys_gpu.yml
  tasks:
    - name: Check if DVM exists
      shell: "qvm-ls --raw-data --fields name | grep -w {{ sys_gpu_dvm }}"
      register: dvm_check
      failed_when: false
      changed_when: false
    - name: Create DVM
      command: qvm-create --class AppVM --label blue --template {{ host_sys_gpu_template }} {{ sys_gpu_dvm }}
      when: dvm_check.rc != 0
    - name: Set DVM label
      command: qvm-prefs {{ sys_gpu_dvm }} label blue
    - name: Set DVM network
      command: qvm-prefs {{ sys_gpu_dvm }} netvm {{ netvm_default }}
    - name: Set as DispVM template
      command: qvm-prefs {{ sys_gpu_dvm }} template_for_dispvms true
    - include_role:
        name: set_prefs
        apply:
          tags: [prefs, sys-gpu]
      tags: [prefs]
      vars:
        target_vm: "{{ sys_gpu_dvm }}"
        vm_qrexec_timeout: "{{ qrexec_timeout_default }}"

#
# DispVM
#
- hosts: local
  connection: local
  vars_files:
    - vars/sys_gpu.yml
  tasks:
    - name: Check if DispVM exists
      shell: "qvm-ls --raw-data --fields name | grep -E '^{{ sys_gpu_dispvm }}$'"
      register: dispvm_check
      failed_when: false
      changed_when: false
    - name: Create DispVM
      command: qvm-create --class DispVM --label red --template {{ sys_gpu_dvm }} {{ sys_gpu_dispvm }}
      when: dispvm_check.rc != 0
    - name: Set default DVM
      command: qvm-prefs {{ sys_gpu_dispvm }} default_dispvm {{ sys_gpu_dvm }}
    - name: Set label
      command: qvm-prefs {{ sys_gpu_dispvm }} label red
    - name: Set HVM mode
      command: qvm-prefs {{ sys_gpu_dispvm }} virt_mode hvm
    - name: Set kernel
      command: qvm-prefs {{ sys_gpu_dispvm }} kernel ''
    - include_role:
        name: set_prefs
        apply:
          tags: [prefs, sys-gpu]
      tags: [prefs]
      vars:
        target_vm: "{{ sys_gpu_dispvm }}"
        vm_qrexec_timeout: "{{ qrexec_timeout_default }}"
        vm_memory: "{{ sys_gpu_memory }}"
        vm_maxmem: "{{ sys_gpu_maxmem }}"
    - name: Attach GPU VGA
      command: qvm-pci attach {{ sys_gpu_dispvm }} dom0:{{ gpu_pci_id_vga }} --persistent
    - name: Attach GPU Audio
      command: qvm-pci attach {{ sys_gpu_dispvm }} dom0:{{ gpu_pci_id_audio }} --persistent
