---
- name: Upgrade system and install base packages
  ansible.builtin.include_role:
    name: common
    tasks_from: packages
  vars:
    packages_upgrade: true
    packages_all: "{{ base_packages + base_packages_playbook_extra }}"
    packages_debian: "{{ base_packages_debian + base_packages_playbook_extra_debian }}"
    packages_redhat: "{{ base_packages_redhat + base_packages_playbook_extra_redhat }}"
